---
- hosts: localhost
  vars:
      package1 : "nginx"
      package2 : "wget"
  tasks:
    - name: Installing package nginx
      apt: pkg=nginx state=installed update_cache=true
    # - name: Instaling Wget
      apt: name={{ package2 }} state=installed update_cache=true
      # become: true
    # - name: