---
- hosts: web_portal
  tasks:
    - name: Apt get update
      apt: name=apache2 update_cache=no

    - name: Copy data files
      copy: src=index.html dest=/var/www/html/

    - name: Stop the service
      service: name=apache2 state=stopped